server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # SADECE blog konteynerinin loglarını al (Diğer eski konteynerleri yoksay)
      - source_labels: ['__meta_docker_container_name']
        regex: '/?portfolio-blog.*'
        action: keep
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_log_path']
        target_label: __path__
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log
      - labels:
          stream:
      # Eski zaman damgası hatalarını yutması için 7 günden eski logları çöpe at
      - drop:
          older_than: 168h
      - match:
          selector: '{container=~"portfolio-blog.*"} |= "[access]"'
          stages:
            - regex:
                expression: '^\[access\] ip=(?P<remote_addr>\S+) method=(?P<method>\S+) path=(?P<path>\S+).*'
            - geoip:
                db: /data/geolite2/GeoLite2-City.mmdb
                source: remote_addr
                db_type: city
            - labels:
                method:
                path:
            - labelallow:
                - container
                - job
                - stream
                - method
                - path
                - geoip_country_name
                - geoip_city_name
                - geoip_continent_code
                - geoip_location_latitude
                - geoip_location_longitude
