{
 "title": "Visitor GeoIP",
 "tags": [ "monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Visitors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\".*blog.*\"} |= \"[access]\" [$__range]))"
    }
   ]
  },
  {
   "title": "Requests by country",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (geoip_country_name) (count_over_time({container=~\".*blog.*\"} |= \"[access]\" [$__range])))"
    }
   ]
  },
  {
   "title": "Requests with GeoIP match",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\".*blog.*\", geoip_country_name=~\".+\"} |= \"[access]\" [$__range]))"
    }
   ]
  },
  {
   "title": "Visitor locations (map)",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=~\".*blog.*\"} |= \"[access]\" | label_format latitude=geoip_location_latitude, longitude=geoip_location_longitude"
    }
   ]
  }
 ]
}